[tool.poetry]
name = "sensors"
version = "0.1.0"
description = ""
authors = ["Tom Homewood"]

[tool.poetry.dependencies]
python = "^3.7"
bme280pi = "1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
